Upstream merge (#15)
* Update multilingual.service.ts (#235)

* Fix for #292, NPM run clean fails with TSError: ⨯ Unable to compile TypeScript (#233)

* Fix #232 - npm run clean fails with compilation error

* Version 2.0.0 of @angular/platform-server

* remove yarn install on travis

* docs: update the list of wiki contributors

* Fix failing AoT build

As of angular/angular b15039d, the 'transitiveModules' option has
been removed from compiler-cli CodeGenerator's 'codegen' method.
The current seed still includes this option, which causes the pr-
oduction AoT build to fail. Removing the option -- just like has
been done in the angular-cli source code -- fixes the production
AoT build.

* docs: drop mit badge

* Fixed tslint settings.
Replaced some tabs to spaces.

* Central state management within core (on a per framework basis) (#304)

* Central state management within core (on a per framework basis)

* Central state management within core (on a per framework basis)

* State tests fixes

* Minor corrections + karma conf to fix references to ngrx-store-freeze and deep-freeze

* Create own framework for AppStateModule

* chore: Angular 2.2.1, NativeScript 2.4.0

* Merge parent seed updates

* AOT compile fix for angular 2.2.3

* fix(aot): set transitive properties

* fix: NativeScript app

* fix: Electron desktop build and Web production build

closes https://github.com/NathanWalker/angular-seed-advanced/issues/309

* Fixed tslint settings.
Replaced some tabs to spaces.

* use v45

* chore: drop useless libs from tsconfig

* feat(tasks): allow easier overriding of existing tasks

Fix #1504

* whitespace cleanup

* tslint did not print the full relative path

* problemMatcher pattern adopted to gulp-tslint
- the rule name is no longer emitted by gulp-tslint and thus the pattern
  needs to be adopted in order that it still works

* refactor template_locals using builder
- the builder enables easier configuration without code duplication
- removed the side effects of Object.assign by introducing new Objects
  (ENV_CONFIG was added to Config previsouly)
- using a unstringified ENV_CONFIG to build index.html enables to refer to
  properties in index.html by <%= ENV_CONFIG.MY_PROPERTY %>

# Conflicts:
#	tools/tasks/seed/build.js.e2e.ts

* chore: consistency, standards and ngrx organization

* chore: consistency

* docs: add missing file description

* example for env-config usage in index.html

* chore: update to tslint 4 and codelyzer 2.0.0-beta.1

* fix: Effects start up procedure (#311)

* chore: update

* docs: use proper command for running compodoc server

* chore: downgrade typescript

Based on https://github.com/angular/angular/issues/12966

* chore: merge upstream parent

* cleanup

* tslint should not lint d.ts files

* note

* fix: npm start and production build

closes https://github.com/NathanWalker/angular-seed-advanced/issues/317
closes https://github.com/NathanWalker/angular-seed-advanced/issues/316

* Intellisense fixes, comments (#315)

* Update app.state.ts

IDE Intellisense fix for .select function

* Update analytics.service.spec.ts

Updated comments ("// angular" for @angular deps).

* Update analytics.service.ts

IDE Intellisense fix for lodash

* Update platform.directive.spec.ts

Updated comments ("// angular" for @angular deps).

* Update console.service.ts

Updated comments ("// angular" for @angular deps).

* Update log.service.spec.ts

Updated comments ("// angular" for @angular deps).

* Update log.service.ts

Updated comments ("// angular" for @angular deps).

* Update router-extensions.service.ts

Updated comments ("// angular" for @angular deps).

* Update window.service.ts

Updated comments ("// angular" for @angular deps).

* Update router-extensions.service.ts

Moved NavigationExtras  from '@angular/router/src/router' to '@angular/router'.

* Update ng2-jasmine.ts

Updated comments ("// angular" for @angular deps).

* Update app.state.ts

Updated comments ("// libs" for library deps).

* Update analytics.service.spec.ts

Updated comments ("// app" for app deps).

* Update analytics.service.ts

Moved Angulartics2Segment from 'angulartics2/dist/providers' to 'angulartics2'.

* Update base.component.ts

Updated comments ("// app" for app deps).

* Update index.ts

Updated comments ("// app" for app deps).

* Update platform.directive.spec.ts

Updated comments ("// app" for app deps).

* Update console.service.ts

Updated comments ("// app" for app deps).

* Update index.ts

Updated comments ("// app" for app deps).

* Update log.service.spec.ts

Updated comments ("// app" for app deps).

* Update log.service.ts

Updated comments ("// app" for app deps).

* Update window.service.ts

Updated comments ("// app" for app deps).

* Update index.ts

Updated comments ("// mocks" for mocks).

* Update router-extensions.mock.ts

Updated comments ("// angular" for @angular deps).

* Update router-extensions.mock.ts

Updated comments ("// app" for app deps).

* Update mock-location-strategy.ts

Moved EventEmitter from '@angular/core/src/facade/async' to '@angular/core'.

* Update config.spec.ts

Updated comments ("// app" for app deps).

* Update config.spec.ts

Updated comments ("// libs" for library deps).

* Update config.spec.ts

IDE Intellisense fix for lodash

* Update view-broker.ts

Updated comments ("// app" for app deps).

* Update view-broker.spec.ts

Updated comments ("// app" for app deps).

* Update multilingual.action.ts

Updated comments ("// libs" for library deps).

* Update multilingual.action.ts

Updated comments ("// app" for app deps).

* Update multilingual.reducer.ts

Updated comments ("// module" for module deps).

* Update multilingual.service.spec.ts

Updated comments ("// app" for app deps).

* Update multilingual.service.spec.ts

Updated comments ("// angular" for @angular deps).

* Update multilingual.service.spec.ts

Updated comments ("// module" for module deps).

* Update ng2-translate.mock.ts

Updated comments ("// angular" for @angular deps).

* Update ng2-translate.mock.ts

Updated comments ("// libs" for library deps).

* Update event.service.ts

Updated comments ("// libs" for library deps).

* Update multilingual.effect.ts

IDE Intellisense fix for .map function (".map(action => {").

* Update analytics.service.ts

(Fallback) IDE Intellisense fix for lodash

* Update config.spec.ts

(Fallback) IDE Intellisense fix for lodash

* Update analytics.service.spec.ts

Updated comments ("// module" for module deps).

* Update base.component.ts

Updated comments ("// module" for module deps).

* Update utils.ts

Updated comments ("// module" for module deps).

* Update platform.directive.spec.ts

Updated comments ("// module" for module deps).

* Update platform.directive.ts

Updated comments ("// module" for module deps).

* Update console.service.ts

Updated comments ("// module" for module deps).

* Update log.service.spec.ts

Updated comments ("// module" for module deps).

* Update log.service.ts

Updated comments ("// module" for module deps).

* Update window.service.ts

Updated comments ("// module" for module deps).

* Update router-extensions.mock.ts

Updated comments ("// module" for module deps).

* Update core.ts

Updated comments ("// module" for module deps).

* Update config.spec.ts

Updated comments ("// module" for module deps).

* Update view-broker.spec.ts

Updated comments ("// module" for module deps).

* Update view-broker.ts

Updated comments ("// module" for module deps).

* Update core.module.ts

Updated comments ("// module" for module deps).

* Update multilingual.action.ts

Updated comments ("// module" for module deps).

* Update multilingual.service.ts

Moved CATEGORY from 'app deps' to 'module deps'

* Update index.ts

Updated comments ("// module" for module deps).

* Update multilingual.module.ts

Updated comments ("// module" for module deps).

* Update analytics.module.ts

Updated comments ("// module" for module deps).

* Add gulp-tslint back in. It now supports tslint v4

* Upgrade compodoc to 0.0.18

The previous locked version `0.0.15` wasn't working on them new nodes
like `7.2.0`.

```
♡  yarn install
yarn install v0.18.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error compodoc@0.0.15: The engine "node" is incompatible with this module. Expected version ">= 5.4.1 < 7".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
♡  node --version
v7.2.0
```

* chore: update lint task in package.json

* chore: update deps, also nativescript-angular next changes

* docs: update wiki contributors

* Moved EnvConfig interface definition from client config directory to env-config.interface.ts in the tools directory so that /tools wasn't referencing src/client.

* chore: update contributors table

* docs: note about compodoc api docs

* fix: update the config demo

* chore: cleanup

* feat: forbid removal of files outside the project root

Fix #1720

* Simplified a couple unit test samples

* Added missing semicolon.

* fix: remove brace after semicolon

* fix: freeze dep

closes https://github.com/NathanWalker/angular-seed-advanced/issues/322

* chore: update deps

* chore: update aot api calls

* Integration with ng2-config (#324)

* chore: ng2-config deps

Signed-off-by: Burak Tasci <me@fulls1z3.com>

* feat: integrate ng2-config with core modules (+lang-switch fix)

Signed-off-by: Burak Tasci <me@fulls1z3.com>

* feat: integrate ng2-config with log-service

Signed-off-by: Burak Tasci <me@fulls1z3.com>

* chore(package.json): modify tslint / @angular/router package versions to fix NPM warnings

* Integrate ng2-config with i18n (#325)

* feat: integrate ng2-config with i18n

Signed-off-by: Burak Tasci <me@fulls1z3.com>

* chore: remove unused imports

Signed-off-by: Burak Tasci <me@fulls1z3.com>

* chore: update contributors table

* fix: config setup

* chore: update dependencies

* chore: update dev dependencies

* chore: update deps

* refactor: drop 2 from angular :christmas_tree:

* chore: add build.prod.aot alias :christmas_tree:

* chore: update systemjs :christmas_tree:

* fix(tools): make sure clean done is a function

Fix #1741

* docs: add basic info about prod build

Fix #1738

* refactor: drop barrels

* chore: drop 2 from all angulars

* fix(spec): broken import

* fix: broken e2e test

* fix: update deps

https://github.com/NathanWalker/angular-seed-advanced/issues/327

* docs: update the list of contributors

* docs: add sample seed project

* chore: update dependencies

* chore: update dev dependencies

* chore: removed ng2-config

closes https://github.com/NathanWalker/angular-seed-advanced/issues/331
closes https://github.com/NathanWalker/angular-seed-advanced/issues/327

* chore: drop reflect-metadata

Fix #1755

* regenerate yarn.lock - fixes #1757

* Fixing issue with protractor, moving up to vrsion 4.0.14

* fix(build): add manual typings for aot

Fix #1763

* docs: update the list of contributors

* Add protractor import statements to e2e specs

TS2304 errors are occurring during the e2e.ci task:

    src/e2e/specs/about.component.e2e-spec.ts(4,18): error TS2304: Cannot find name 'browser'.
    ...

The webstorm editor also shows import error warnings, which can be
distracting.

This may be because @types/protractor was removed. The 'protractor'
module now contains the necessary typings.

Adding an import statement silenced the webstorm editor warnings as
well as the TS2304 warnings that occurred during e2e.ci execution.

* chore: update deps

* chore: use tns run instead of emulate

* Missing merges...